version: 2
jobs:
  test:
      machine:
        image: circleci/classic:edge
      steps:
        - checkout
        - run:
            name: "run test"
            command: |
              go test
  deploy:
    working_directory: ~/go/src/github.com/Matsushin/go-ecs-deploy
    docker:
      - image: circleci/python:2.7-node-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run: sudo pip install awscli
      - run: $(aws ecr get-login --region ap-northeast-1 --no-include-email)
      - run:
          name: Build ECR API
          command: |
            docker build -f ./Dockerfile  -t go-ecs-deploy-app .
      - run:
          name: TAG ECR API
          command: |
            docker tag go-ecs-deploy-app $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/go-ecs-deploy-app:latest
      - run:
          name: Deploy
          command: |
            export AWS_DEFAULT_REGION="ap-northeast-1"
            bash ./deploy.sh

# Workflows
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master