version: 2
jobs:
  ecr-deploy:
    working_directory: ~/go/src/github.com/Matsushin/go-ecs-deploy
    docker:
      - image: circleci/python:2.7-node-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run: sudo pip install awscli
      - run: $(aws ecr get-login --region ap-northeast-1 --no-include-email)
      - run:
          name: Build ECR API
          command: |
            docker build -f ./Dockerfile  -t go-ecs-deploy-app .
      - run:
          ame: TAG ECR API
          command: |
            docker tag go-ecs-deploy-app $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/go-ecs-deploy-app:latest
      - run:
          name: Deploy
          command: |
            bash ./deploy.sh

# Workflows
workflows:
  version: 2
  ecr-deploy:
    jobs:
      - ecr-deploy:
          filters:
            branches:
              only:
                - master